- .travis.yml
- src/github.com/travis-ci/jupiter-brain/vsphere.go
Whenever we don't return an instance from Start(), one shouldn't be left around in vSphere, so make an attempt to find the instance we cloned and then Terminate it if it exists.
> Attempt to terminate instances if an error occurred while cloning

- .travis.yml
- src/github.com/travis-ci/jupiter-brain/server/database.go
This should prevent runaway connection counts in case a connection isn't returned to the pool, or a high number of requests are made at once.
I'm not 100% sure about the exact number "20", but if I recall correctly, that's the pool size we use in other apps?
> server/database: add a limit to the number of open DB connections

- cmd/jb-server/main.go
Makes it possible to see if Jupiter Brain picked up the Librato configuration or not. Without this you don't know if metrics not appearing is due to them never being sent due to an error or because the reporter never started.
> metrics: log when the librato reporter starts

- .travis.yml
- server/server.go
- vendor/manifest
Since we boot/terminate instances in the same process with the HTTP server, we need to make sure to gracefully shut down instead of doing a forceful shutdown, otherwise in-flight requests such as instance creation would be orphaned and the resulting VM would be a "leaked" VM.
We're already using the manners library, which is supposed to implement this, but for it to work we need to call Close() on the GracefulServer instead of just doing os.Exit.
I also updated the manners library to the latest version, since the API changed a bit and there are quite a few improvements.
Fixes #22, #23.
I'd like to attempt to deploy this early next week. We should also make sure that #23 is resolved before deploying this, and maybe add some shorter timeouts, otherwise a restart could take a long time.
> Graceful shutdown

- cmd/jb-server/main.go
- server/config.go
- server/server.go
- vsphere.go
This adds three concurrency limiters to Jupiter Brain. With the default values, it'll have the following effect:
- No more than 4 concurrent "read" requests (list and fetch, although list requests are incredibly rare, so effectively mostly limiting fetch)
- No more than 48 concurrent "create" requests.
- No more than 48 concurrent "destroy" requests.
Notably the create and destroy requests are considered to be running all the way until the underlying vSphere task is finished, not just when the HTTP request is finished, so if they start to take longer that's gonna provide some pushback and should prevent the snowball effect we see now when things start to get slow and requests time out and requeues happen.
r? @solarce Did we want any more metrics on this? I can't quite remember what we …
> Add a max concurrency limiter

- vsphere.go
This metric includes the time it takes to wait for the concurrency limiter, clone the VM and power it on. We have metrics for each of those individually, but not for the sum of them.
> Add metric for "full start"

- cmd/jb-server/main.go
- server/config.go
- server/server.go
The pprof handlers don't work well with negroni and middleware, so moving it to a raw http Server should work better.
> pprof: move pprof listener to separate port

- server/response_metrics.go
- server/server.go
This allows us to see how many requests are succeeding/passing/failing/etc.
> server: add metric for response codes

- cmd/jb-server/main.go
- server/config.go
- server/server.go
Defaults to 3 minutes, the old value, but is now configurable. This only applies to the timeout for incoming HTTP requests.
> Make the request timeout configurable

- vendor/manifest
The code change from the fork was merged, so we can use upstream again.
Closes #35.
> Revert back to upstream govmomi

- server/server.go
If the request timeout is longer than the write timeout, the HTTP connection can get closed due to the response not being written in time.
> server: change http write timeout to request timeout + 10 seconds

- cmd/jb-server/main.go
- vsphere.go
Sets the Sentry DSN globally so we can send things to Sentry, and makes sure we don't send errors to Sentry for context cancellations.
> Minor fixes to Sentry logic

- cmd/jb-server/main.go
This should let us be able to track which version an error happened in in Sentry.
> sentry: set the version in the release field

- cmd/jb-server/main.go
- jbcontext/package.go
- server/response_metrics.go
- server/server.go
- vendor/manifest
- vsphere.go
This PR adds some Honeycomb integration. It sends the following events:
- clone
- terminate
- http-request
All events contain the `X-Request-ID` value if the HTTP header is set (we don't set this anywhere yet, but that way it's tracked when we start to do that).
The HTTP request event has information about the request duration, the HTTP method, URL path (e.g. `/instances/fafafafa-fafa-fafa-fafa-fafafafafafa`), response code (e.g. `200`), and the number of bytes written.
The clone event differs a bit in information depending on how far in the clone it gets. It always has the image name, total duration, whether the clone succeeded or failed (and the error if it failed), and a string field that specifies how far the clone got (roughly "where did the `Start()` method return).
In addition, it …
> Add some initial Honeycomb support

- vsphere.go
This allows us to check which host the VM eventually ended up on.
> Use background context when getting powered on VM hostname

- .travis.yml
- server/server.go
Right now Sentry sends the stacktrace to the place where `raven.CaptureError` is called, which is less useful than the source of the error itself.
> Send stacktrace from errors to Sentry if available

- cmd/jb-server/main.go
- server/config.go
- server/negroniraven/middleware.go
- server/server.go
Passing in the environment name allows us to notice if an error affects one environment over another, or we could potentially ignore alerts for staging warnings, or send them elsewhere, etc.
> Pass environment name to Sentry

- server/server.go
The frame returned by NewStacktraceFrame can be nil in certain cases, for example for `runtime.goexit`. The `raven.NewStacktrace` function handles them by just skipping over them in the stacktrace, so let's port that into this as well.
> Fix runtime panic in Sentry stacktrace creator

- cmd/jb-server/main.go
- server/config.go
- server/database.go
- server/server.go
https://github.com/travis-pro/team-blue/issues/692
The configurable value has been set to 2 from 20 to prevent connection overload for our limit of 500.
> Database Connection Pool Reduce and Configuration for JB

- instance.go
- instance_manager.go
- server/server.go
- server/server_test.go
- vsphere.go
Adds some new optional fields to the create instance request payload: `cpus` and `ram`. If either is present, the instance will be reconfigured appropriately to have a different number of CPUs or different amount of RAM. Any field that isn't set will default to what the base VM has.
The intention is that we will make changes in worker to be able to experiment with these parameters, and eventually introduce rules that change this based on the job.
> Allow configuring CPUs and RAM for created VMs

- pkg/vsphereutil/client_provider.go
- vsphere.go
Create a vsphereutil package for things that are generally useful when working with vSphere, even outside jupiter-brain.
This package can be imported by other services, so I intend to use this `ClientProvider` abstraction in both vsphere-monitor and vsphere-janitor.
> Extract ClientProvider
